import type { Item } from './types';
export const demoItems: Item[] = [
 {id:'demo-1',owner_id:'demo-a',title:'Sony WH-1000XM4',description:'سماعات بعزل ضوضاء، مع الحافظة والشاحن. استخدام خفيف، وبطارية بحالة جيدة. صور ومعلومات توضيحية لتجربة الموقع.',category:'electronics',wanted_categories:['gaming','books'],wanted_text:'Kindle أو Nintendo Switch',city:'رام الله',condition:'كأنه جديد',image_url:'https://images.unsplash.com/photo-1546435770-a3e426bf472b?auto=format&fit=crop&w=800&q=85',owner_name:'أحمد',status:'available',created_at:'2026-10-01'},
 {id:'demo-2',owner_id:'demo-b',title:'Nintendo Switch',description:'الجهاز مع يدّي تحكم وقاعدة التوصيل. خدوش استخدام بسيطة. هذا إعلان توضيحي وليس عرضًا حقيقيًا.',category:'gaming',wanted_categories:['electronics'],wanted_text:'سماعات لاسلكية أو تابلت',city:'رام الله',condition:'جيد جدًا',image_url:'https://images.unsplash.com/photo-1578303512597-81e6cc155b3e?auto=format&fit=crop&w=800&q=85',owner_name:'سارة',status:'available',created_at:'2026-10-02'},
 {id:'demo-3',owner_id:'demo-c',title:'مجموعة كتب لوقت أهدأ',description:'مجموعة كتب متنوعة بحالة ممتازة، دون كتابة على الصفحات. إعلان توضيحي.',category:'books',wanted_categories:['books'],wanted_text:'روايات عربية أو كتب تصميم',city:'الخليل',condition:'جيد جدًا',image_url:'https://images.unsplash.com/photo-1507842217343-583bb7270b66?auto=format&fit=crop&w=800&q=85',owner_name:'ليان',status:'available',created_at:'2026-10-03'},
 {id:'demo-4',owner_id:'demo-d',title:'كاميرا Fujifilm',description:'كاميرا للهواة مع العدسة وحزام الكتف. تفاصيل توضيحية لتجربة التصفح.',category:'electronics',wanted_categories:['electronics','gaming'],wanted_text:'iPad أو جهاز ألعاب',city:'نابلس',condition:'جيد',image_url:'https://images.unsplash.com/photo-1516035069371-29a1b244cc32?auto=format&fit=crop&w=800&q=85',owner_name:'عمر',status:'available',created_at:'2026-10-04'},
 {id:'demo-5',owner_id:'demo-e',title:'يد تحكم PlayStation 5',description:'يد تحكم لاسلكية، جميع الأزرار تعمل. إعلان توضيحي غير متاح للتبادل الفعلي.',category:'gaming',wanted_categories:['gaming','electronics'],wanted_text:'ألعاب PS5 أو سماعات',city:'بيت لحم',condition:'كأنه جديد',image_url:'https://images.unsplash.com/photo-1606318801954-d46d46d3360a?auto=format&fit=crop&w=800&q=85',owner_name:'نور',status:'available',created_at:'2026-10-05'},
 {id:'demo-6',owner_id:'demo-f',title:'ركن القراءة الخاص فيك',description:'كتب مستعملة بعناية، مناسبة لبداية مكتبة جديدة. إعلان توضيحي.',category:'books',wanted_categories:['books','electronics'],wanted_text:'كتب أخرى أو قارئ إلكتروني',city:'رام الله',condition:'جيد',image_url:'https://images.unsplash.com/photo-1491841550275-ad7854e35ca6?auto=format&fit=crop&w=800&q=85',owner_name:'دانا',status:'available',created_at:'2026-10-06'}
];
